# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTeacher(object):
    def setupUi(self, AddTeacher):
        AddTeacher.setObjectName("AddTeacher")
        AddTeacher.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(AddTeacher)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.surname_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.surname_edit.setObjectName("surname_edit")
        self.gridLayout.addWidget(self.surname_edit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.patronymic_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.patronymic_edit.setObjectName("patronymic_edit")
        self.gridLayout.addWidget(self.patronymic_edit, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        AddTeacher.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddTeacher)
        self.statusbar.setObjectName("statusbar")
        AddTeacher.setStatusBar(self.statusbar)

        self.retranslateUi(AddTeacher)
        QtCore.QMetaObject.connectSlotsByName(AddTeacher)

    def retranslateUi(self, AddTeacher):
        _translate = QtCore.QCoreApplication.translate
        AddTeacher.setWindowTitle(_translate("AddTeacher", "Добавить учителя"))
        self.label_2.setText(_translate("AddTeacher", "Введите фамилию"))
        self.label.setText(_translate("AddTeacher", "Введите имя"))
        self.label_3.setText(_translate("AddTeacher", "Введите отчество"))
        self.pushButton.setText(_translate("AddTeacher", "Готово"))
