# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Enter):
        Enter.setObjectName("Enter")
        Enter.resize(323, 324)
        self.centralwidget = QtWidgets.QWidget(Enter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.gridLayout.addWidget(self.password_edit, 2, 1, 1, 1)
        self.teacher_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.teacher_btn.setObjectName("teacher_btn")
        self.gridLayout.addWidget(self.teacher_btn, 0, 0, 1, 1)
        self.group_label = QtWidgets.QLabel(self.centralwidget)
        self.group_label.setObjectName("group_label")
        self.gridLayout.addWidget(self.group_label, 3, 0, 1, 1)
        self.student_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.student_btn.setObjectName("student_btn")
        self.gridLayout.addWidget(self.student_btn, 0, 1, 1, 1)
        self.login_label = QtWidgets.QLabel(self.centralwidget)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 1, 0, 1, 1)
        self.group_box = QtWidgets.QComboBox(self.centralwidget)
        self.group_box.setObjectName("group_box")
        self.gridLayout.addWidget(self.group_box, 3, 1, 1, 1)
        self.login_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_edit.setObjectName("login_edit")
        self.gridLayout.addWidget(self.login_edit, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 2, 0, 1, 1)
        self.hide_password_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hide_password_btn.setObjectName("hide_password_btn")
        self.gridLayout.addWidget(self.hide_password_btn, 2, 2, 1, 1)
        Enter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Enter)
        self.statusbar.setObjectName("statusbar")
        Enter.setStatusBar(self.statusbar)

        self.retranslateUi(Enter)
        QtCore.QMetaObject.connectSlotsByName(Enter)

    def retranslateUi(self, Enter):
        _translate = QtCore.QCoreApplication.translate
        Enter.setWindowTitle(_translate("Enter", "Вход"))
        self.teacher_btn.setText(_translate("Enter", "Я учитель"))
        self.group_label.setText(_translate("Enter", "Выберите группу"))
        self.student_btn.setText(_translate("Enter", "Я ученик"))
        self.login_label.setText(_translate("Enter", "Логин:"))
        self.pushButton.setText(_translate("Enter", "Готово"))
        self.password_label.setText(_translate("Enter", "Пароль:"))
        self.hide_password_btn.setText(_translate("Enter", "Показать пароль"))
