# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.registration_profile_btn = QtWidgets.QPushButton(self.centralwidget)
        self.registration_profile_btn.setText("")
        self.registration_profile_btn.setObjectName("registration_profile_btn")
        self.gridLayout.addWidget(self.registration_profile_btn, 0, 0, 1, 1)
        self.enter_exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.enter_exit_btn.setText("")
        self.enter_exit_btn.setObjectName("enter_exit_btn")
        self.gridLayout.addWidget(self.enter_exit_btn, 0, 1, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 2, 2, 2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(329, 383))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 3, 2)
        self.add_class_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_class_btn.setObjectName("add_class_btn")
        self.gridLayout.addWidget(self.add_class_btn, 2, 2, 1, 1)
        self.remove_class_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_class_btn.setObjectName("remove_class_btn")
        self.gridLayout.addWidget(self.remove_class_btn, 2, 3, 1, 1)
        self.classes_list = QtWidgets.QListWidget(self.centralwidget)
        self.classes_list.setMaximumSize(QtCore.QSize(16777215, 50))
        self.classes_list.setObjectName("classes_list")
        self.gridLayout.addWidget(self.classes_list, 3, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ваше расписание IT-Куба"))
        self.add_class_btn.setText(_translate("MainWindow", "Добавить занятие"))
        self.remove_class_btn.setText(_translate("MainWindow", "Удалить занятие"))
