# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(367, 450)
        self.centralwidget = QtWidgets.QWidget(Registration)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.gridLayout.addWidget(self.error_label, 6, 0, 1, 2)
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.gridLayout.addWidget(self.password_edit, 5, 1, 1, 1)
        self.hide_password_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hide_password_btn.setObjectName("hide_password_btn")
        self.gridLayout.addWidget(self.hide_password_btn, 5, 2, 1, 1)
        self.login_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_edit.setObjectName("login_edit")
        self.gridLayout.addWidget(self.login_edit, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.patronymic_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.patronymic_edit.setObjectName("patronymic_edit")
        self.gridLayout.addWidget(self.patronymic_edit, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.surname_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.surname_edit.setObjectName("surname_edit")
        self.gridLayout.addWidget(self.surname_edit, 0, 1, 1, 1)
        Registration.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Registration)
        self.statusbar.setObjectName("statusbar")
        Registration.setStatusBar(self.statusbar)

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Регистрация"))
        self.label.setText(_translate("Registration", "Введите имя"))
        self.label_6.setText(_translate("Registration", "Введите отчество"))
        self.hide_password_btn.setText(_translate("Registration", "Показать пароль"))
        self.label_3.setText(_translate("Registration", "Придумайте логин"))
        self.label_4.setText(_translate("Registration", "Придумайте пароль"))
        self.pushButton.setText(_translate("Registration", "Зарегистрироваться"))
        self.label_2.setText(_translate("Registration", "Введите фамилию"))
