# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remove_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveClass(object):
    def setupUi(self, RemoveClass):
        RemoveClass.setObjectName("RemoveClass")
        RemoveClass.resize(333, 242)
        self.centralwidget = QtWidgets.QWidget(RemoveClass)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.classes_box = QtWidgets.QComboBox(self.centralwidget)
        self.classes_box.setObjectName("classes_box")
        self.gridLayout.addWidget(self.classes_box, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        RemoveClass.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RemoveClass)
        self.statusbar.setObjectName("statusbar")
        RemoveClass.setStatusBar(self.statusbar)

        self.retranslateUi(RemoveClass)
        QtCore.QMetaObject.connectSlotsByName(RemoveClass)

    def retranslateUi(self, RemoveClass):
        _translate = QtCore.QCoreApplication.translate
        RemoveClass.setWindowTitle(_translate("RemoveClass", "Удаление занятия"))
        self.label.setText(_translate("RemoveClass", "Выберите занятие"))
        self.pushButton.setText(_translate("RemoveClass", "Готово"))
